this_plugin:
  security_key: KabcD5534EUYyyt
  delete_self: false
  allow_remote: true
  master_name: Best Beef and Burger
  master_url: 'https://news.google.com'

user:
  contact_person: Will Woodlief
  contact_company: Texas Sofware
  contact_url: 'https://texdevelopers.com'

options:

  - option_key: gmt_offset
    option_value: __RESET__

  - option_key: blogname
    option_value: Will's Blog?


  - option_key: require_name_email
    option_value: 1



plugins:


#  - name: Random Thing
#    slug: duplicate-post
#    action: 'delete'




themes:
  - name: Sample Theme
    slug: twentyseventeen
    action: switch
